### ISSUE TITLE
Error When run in android

### ISSUE THREAD

**Issue by havudk1707** [adjapon/ViidleSDK-Unity-Sample#1]
Hi,
I have error when I tried to run in Android device.
In my case, I just created test project without real app in google play, imported package, followed your code and build.
Unity: 5.4.3p4

CommandInvokationFailure: Failed to re-package resources.
/Users/vuha/Library/Android/sdk/build-tools/25.0.2/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/vuha/Library/Android/sdk/platforms/android-25/android.jar" -F bin/resources.ap_ --extra-packages net.viidle.android:net.viidle.unity.plugin -S "/Users/vuha/Documents/Dev/Github/TestViidleAds/Temp/StagingArea/android-libraries/viidle-sdk-1.0.1/res" -S "/Users/vuha/Documents/Dev/Github/TestViidleAds/Temp/StagingArea/android-libraries/viidle-unity-plugin/res"

stderr[
/Users/vuha/Documents/Dev/Github/TestViidleAds/Temp/StagingArea/android-libraries/viidle-sdk-1.0.1/res/layout/viidle_sdk_test_mode_mediation.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Users/vuha/Documents/Dev/Github/TestViidleAds/Temp/StagingArea/android-libraries/viidle-sdk-1.0.1/res/layout/viidle_sdk_test_mode_mediation.xml: note: using v17 attributes; synthesizing resource com.seec.viidletest:layout/viidle_sdk_test_mode_mediation for configuration v17.
/Users/vuha/Documents/Dev/Github/TestViidleAds/Temp/StagingArea/android-libraries/viidle-sdk-1.0.1/res/layout/viidle_sdk_test_mode_top.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Users/vuha/Documents/Dev/Github/TestViidleAds/Temp/StagingArea/android-libraries/viidle-sdk-1.0.1/res/layout/viidle_sdk_test_mode_top.xml: note: using v17 attributes; synthesizing resource com.seec.viidletest:layout/viidle_sdk_test_mode_top for configuration v17.
AndroidManifest.xml:37: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: /Users/vuha/Library/Android/sdk/platforms/android-25/android.jar
applyFileOverlay for drawable
trying overlaySet Key=viidle_sdk_button_selector.xml
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
trying overlaySet Key=viidle_sdk_test_mode_mediation.xml
trying overlaySet Key=viidle_sdk_test_mode_top.xml
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res/drawable-xhdpi/app_banner.png
Processing image: res/drawable-mdpi/app_icon.png
    (processed image res/drawable-mdpi/app_icon.png: 90% size of source)
    (processed image res/drawable-xhdpi/app_banner.png: 93% size of source)
    (new resource id app_banner from xhdpi-v4/drawable/app_banner.png #generated)
    (new resource id app_icon from mdpi-v4/drawable/app_icon.png #generated)
    (new resource id viidle_sdk_button_selector from /Users/vuha/Documents/Dev/Github/TestViidleAds/Temp/StagingArea/android-libraries/viidle-sdk-1.0.1/res/drawable/viidle_sdk_button_selector.xml)
    (new resource id viidle_sdk_test_mode_mediation from /Users/vuha/Documents/Dev/Github/TestViidleAds/Temp/StagingArea/android-libraries/viidle-sdk-1.0.1/res/layout/viidle_sdk_test_mode_mediation.xml)
    (new resource id viidle_sdk_test_mode_top from /Users/vuha/Documents/Dev/Github/TestViidleAds/Temp/StagingArea/android-libraries/viidle-sdk-1.0.1/res/layout/viidle_sdk_test_mode_top.xml)
]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessor.Tasks.TasksCommon.Exec (System.String command, System.String args, System.String workingdir, System.String errorMsg, Int32 retiresOnFailure)
UnityEditor.HostView:OnGUI()

Can you help me!
Thanks...

**Comment by fan-c-yu** [comment]
Hi,

Thanks for reaching out.

It seems to be the reason that `google_play_services` has not been imported.

Please refer to the following guidelines.
https://github.com/adjapon/ViidleSDK-Unity-Sample/wiki/Import-Unity-Package#set-up-for-android

Hope it's helpful.

Best regards.
viidle Support Team

**Comment by havudk1707** [comment]
Hi,
This is my mistake.
Thanks for support me.
Best regards.
